filters:
  - label: ğŸ”¥bug
    regexs:
      - /\bfix\b|bug/
    events: [issues, pull_request]
    targets: [title, comment]
  - label: ğŸš€feature
    regexs:
      - /\bfeat\b|feat/
  - label: ğŸ“docs
    regexs:
      - /\bdocs\b|docs/
  - label: ğŸš§chore
    regexs:
      - /\bchore\b|chore/
  - label: ğŸšinfra
    regexs:
      - /\binfra\b|infra/
  - label: âœ…test
    regexs:
      - /\btest\b|test/